name: Update Mammoth Weather Screenshot

# grant write permission so the bot can push weather.png
permissions:
  contents: write

on:
schedule:
- cron: '0 0,8,16 * * *'  # at 00:00, 08:00 and 16:00 every day
  workflow_dispatch:         # allows manual trigger

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Mammoth screenshot
        run: node screenshot-mammoth.js

      - name: Commit and push Mammoth png
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add weather-mammoth.png
          git commit -m "chore: update weather-mammoth.png [skip ci]" || echo "No changes to commit"
          git push
